#!/bin/bash

set -e

if [ "$1" = "" ]; then
    echo "usage: build PROG"
    exit 1
fi

prog=$1

../compiler/slangc $prog.sl > $prog.s
../compiler/peepopt $prog.s | ../compiler/peepopt > $prog.opt.s
cat lib/head.s $prog.opt.s lib/foot.s | ../asm/asm -v > $prog.anhex &
cat lib/head.s $prog.opt.s lib/foot.s | ../asm/asm > $prog.hex
../util/hex2bin $prog.hex > $prog.bin
