#!/bin/bash

# if you add something here you also need to add a line to ../kernel/fs.in to put
# an empty file in /lib/foo.h
LIBS="grarr.sl malloc.sl parse.sl stdio.sl stdlib.sl string.sl sys.sl xprintf.sl strbuf.sl bufio.sl hash.sl xscanf.sl bitmap.sl"

makelib() {
    name=$1
    shift

    echo " ... makelib $name"

    for f in $LIBS $*;
    do
        echo "include \"$f\";"
    done > lib$name.sl

    ../compiler/slangc --consts-list lib$name.const lib$name.sl | ../compiler/peepopt | ../compiler/peepopt > lib$name.s.build

    cat lib/libhead.s lib$name.s.build | ../asm/asm --externs-list lib$name.list > lib$name.hex.tmp
    ../util/hex2bin lib$name.hex.tmp > lib$name.o.tmp
    mv lib$name.o.tmp lib$name.o
    cat lib/libhead.s lib$name.s.build | ../asm/asm -v > lib$name.anhex
}

makelib "" &
makelib fixed fixed.sl &
makelib bigint bigint.sl &
makelib bigfix bigint.sl fixed.sl &

wait
