#!/bin/sh

# if you add something here you also need to add a line to ../kernel/fs.in to put
# "include-lib.h" in /lib/foo.h
LIBS="grarr.sl malloc.sl parse.sl stdio.sl stdlib.sl string.sl sys.sl xprintf.sl strbuf.sl bufio.sl bigint.sl hash.sl xscanf.sl"

for f in $LIBS;
do
    echo "include \"$f\";"
done > lib.sl

../compiler/slangc lib.sl | ../compiler/peepopt | ../compiler/peepopt > lib.s.build
cat lib/libhead.s lib.s.build | ../asm/asm --asm-header lib.s.tmp --slang-header lib.h > lib.hex.tmp
cat lib.s.head lib.s.tmp > lib.s
../util/hex2bin lib.hex.tmp > lib.o.tmp
mv lib.o.tmp lib.o
cat lib/libhead.s lib.s.build | ../asm/asm -v > lib.anhex
