#!/usr/bin/perl

use strict;
use warnings;

open(my $fh, '<', 'libbigint.h')
    or die "can't read libbigint.h: $!\n";
while (<$fh>) {
    chomp;
    if (/^extern ([a-zA-Z0-9_]+);$/) {
        print "addglobal(\"$1\", &$1);\n";
    } else {
        print STDERR "unrecognised: $_\n";
    }
}
