#!/usr/bin/perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/lib/";

use SCAMP::AdventOfCode;
use SCAMP::Files;
use SCAMP::Serial;

my $serial = SCAMP::Serial->new(*STDIN, *STDOUT);

my $aoc = SCAMP::AdventOfCode->new();
-f "$ENV{HOME}/.aoc-session" or die "Please write your Advent of Code session cookie value to $ENV{HOME}/.aoc-session\n";
$aoc->read_session("$ENV{HOME}/.aoc-session");
$aoc->attach($serial);

my $files = SCAMP::Files->new();
$files->attach($serial);

$serial->run;
