#!/usr/bin/perl

use strict;
use warnings;

use FindBin;
use JSON qw(decode_json);

my $instructions_json;
my $instructions = load_instructions();
my %op2inst = map { $instructions->{$_}{opcode} => $_ } keys %$instructions;

print header();
print "<table>\n";
print "<tr><td></td>";
print "<th>_$_</th>" for (qw(0 1 2 3 4 5 6 7 8 9 a b c d e f));
print "</tr>\n";
for my $a (qw(0 1 2 3 4 5 6 7 8 9 a b c d e f)) {
    print "<tr><th>${a}_</th>";
    for my $b (qw(0 1 2 3 4 5 6 7 8 9 a b c d e f)) {
        my $opcode = "$a$b";
        my $inst = $op2inst{hex($opcode)}||'';
        my $i = $instructions->{$inst};

        $inst =~ s/\(i8h\)/r/g;

        my @clobbers = @{ $i->{clobbers}||[] };
        @clobbers = grep {!/x/} @clobbers if $inst =~ /^\S+ x\b/;
        @clobbers = grep {!/y/} @clobbers if $inst =~ /^\S+ y\b/;
        my $clobber_warnings = join('', map { "<span class=\"clob$_\">*</span>" } sort @clobbers);
        @clobbers = ('(none)') if !@clobbers;
        my $clobbers = join(',', map { "<span class=\"clob$_\">$_</span>" } sort @clobbers);

        my $microcode = join('<br>', map { "&nbsp;&nbsp;$_" } @{ $i->{ucode}||[] });

        my $remark = $i->{remark}||'';

        my ($instop, $instargs) = split / /, $inst, 2;
        $instop ||= '';
        $instargs ||= '';

        my $instopcss = $instop;
        $instopcss = 'j' if $instop =~ /^j/;
        $instopcss = 'tbsz' if $instop eq 'sb';

        $i->{words} ||= '';
        $i->{cycles} ||= '';

        print "<td class=\"inst inst-$instopcss\"><div style=\"padding:2px\"><span style=\"font-weight:bold\">$instop</span> $instargs $clobber_warnings</div><div class=\"popup\"><b>Opcode:</b> $opcode<br><b>Words:</b> $i->{words}<br><b>Cycles:</b> $i->{cycles}<br><b>Clobbers:</b> $clobbers<b><br>Microcode:</b><br>$microcode<br><span class=\"remark\">$remark</span></div></td>";
    }
    print "</tr>\n";
}
print "</table>\n";
print "<div class=\"clobx\">* clobbers x</div>\n";
print "<div class=\"clobr254\">* clobbers r254</div>\n";
print "<div class=\"cloby\">* clobbers y</div>\n";
print footer();

sub header {
    qq{<html>
<head>
<title>Instruction set cheatsheet</title>
<style type="text/css">
table {
    margin-right: 150px;
    font-size: 1.0em;
    font-family: monospace;
}
td {
    background-color: #ccc;
    color: black;
    padding: 2px;
}
td.inst-add { background-color: #dcc; }
td.inst-inc { background-color: #cbb; }
td.inst-sub { background-color: #cdc; }
td.inst-dec { background-color: #bcb; }
td.inst-and { background-color: #ccd; }
td.inst-not { background-color: #bbc; }
td.inst-or { background-color: #ddc; }
td.inst-nand { background-color: #cdd; }
td.inst-nor { background-color: #dcd; }
td.inst-xor { background-color: #bcd; }
td.inst-in { background-color: #ccb; }
td.inst-out { background-color: #bcc; }
td.inst-ld { background-color: #bdc; }
td.inst-push, td.inst-pop, td.inst-ret { background-color: #cbc; }
td.inst-j { background-color: #dcb; }
td.inst-shl, td.inst-shl2, td.inst-shl3 { background-color: #cbd; }
td.inst-tbsz { background-color: #cdb; }

td.inst:hover {
    background-color: #eee;
}
td.inst:hover div.popup {
    display: block;
}
td.inst div.popup {
    display:none;
}
div.popup {
    pointer-events: none;
    position: absolute;
    background: #eee;
    width: 200px;
    padding: 2px;
}
th {
    background-color: #333;
    color: #ccc;
}
.clobr254 {
    color: #a50;
}
.clobx {
    color: #f00;
    font-weight: bold;
}
.cloby {
    color: #888;
}
.remark {
    font-family: sans-serif;
    font-size: 0.8em;
}
tt {
    font-weight: bold;
    font-size: 1.2em;
}
</style>
</head>
<body>
<h1>Instruction set cheatsheet</h1>
<ul>
<li>The instruction word is the opcode shifted left by 8 bits, so opcode <tt>04</tt> becomes <tt>0400</tt>.</li>
<li>Typically the first parameter is the destination and first operand, and the second parameter is the other operand.</li>
<li><tt>i8l</tt> and <tt>i8h</tt> parameters are stored in the lower 8 bits of the instruction word, so <tt>add x, 5</tt> becomes
<tt>0405</tt>. <tt>i8h</tt> is the same as <tt>i8l</tt> except it sets the upper 8 bits to 1, so <tt>add x, 0xff05</tt> becomes <tt>0505</tt>.
They can also be used via <tt>(i16)</tt> parameters.</li>
<li>Side effects on <tt>x</tt>, <tt>r254</tt>, or <tt>y</tt> are documented as "clobbers". Generally
<tt>x</tt> is the only one to worry about.</li>
<li><tt>++</tt> and <tt>--</tt> refer to pre-/post- increment/decrement of a value or pointer.</li>
</ul>
};
}

sub footer {
    qq{<ul>
<li>The <tt>x</tt> register functions as an accumulator.</li>
<li>The <tt>y</tt> register is only exposed for the <tt>xor x, y</tt> instruction, because
<tt>xor x, r</tt> would take too many cycles.</li>
<li><tt>r</tt> parameters are "pseudo-registers", which are any word in the top 256 words of memory, equivalent to <tt>(i8h)</tt>.
<tt>r0</tt> is the same as <tt>(0xff00)</tt>, <tt>r1</tt> is <tt>(0xff01)</tt>, and so on.
<li><tt>r0</tt> to <tt>r253</tt> are free for general purposes.</li>
<li><tt>r254</tt> is used as scratch space for <tt>xor</tt> and as the implicit operand for <tt>sb</tt>.</li>
<li><tt>r255</tt> is the stack pointer, also called <tt>sp</tt>.</li>
</ul></body>
</html>
};
}

sub load_instructions {
    my $file = $FindBin::Bin . "/instructions.json";
    open(my $fh, '<', $file)
        or die "can't read $file: $!";
    $instructions_json = join('', <$fh>);
    close $fh;
    return decode_json($instructions_json);
}
