#!/usr/bin/perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/lib/";

use SLANG::Tex qw(texescape template slurp);

my $src = slurp("../sys/make-lib");

die "can't understand ../sys/make-lib"
    unless $src =~ /LIBS="(.*)"/;

my @libs = split / /, $1;
print "\\tt{$_}\n" for sort @libs;
