#!/usr/bin/perl

# make a blank filesystem

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/lib/";

use SCAMP::FS;

my $fs = SCAMP::FS->new("/dev/zero");

# TODO: [nice] get these constants from SCAMP::FS instead of hardcoding
my $BLKSZ = 512;
my $SKIP_BLOCKS = 64;
my $BITMAP_BLOCKS = 16;
my $FS_SIZE = $BLKSZ * 65536;

# skipped blocks (to store the kernel), bitmap blocks, and root block are all used
$fs->setblkused($_, 1) for (0..80);

# sanity check
my $ok = 1;
for my $i (0..80) {
    if ($fs->blkisfree($i)) {
        $ok = 0;
        print STDERR "block $i shouldn't be free\n";
    }
}
for my $i (81 .. 65535) {
    if (!$fs->blkisfree($i)) {
        $ok = 0;
        print STDERR "block $i should be free\n";
    }
}
exit(1) if !$ok;

# root directory gets "." and ".." entries
$fs->add_dirent(80, ".", 80);
$fs->add_dirent(80, "..", 80);

$fs->{file} = '/dev/stdout';
$fs->save();
