#!/bin/bash
# Run a source file in the emulator, with profiling

set -e

if [ "$1" = "" ]; then
    echo "usage: profrun foo.sl"
    exit 1
fi

echo slangc... >&2
./slangc < $1 > $1.s
echo peepopt... >&2
./peepopt $1.s | ./peepopt > $1.opt.s
echo asm... >&2
cat head.s $1.opt.s foot.s | ../asm/asm > $1.hex
echo asm -v... >&2
cat head.s $1.opt.s foot.s | ../asm/asm -v > $1.anhex
echo emulator... >&2
../emulator/scamp -r $1.hex -c -p $1.prof
echo profhtml... >&2
../emulator/profhtml -x $1.anhex $1.prof > $1.prof.html
echo xdg-open... >&2
xdg-open $1.prof.html
