#!/bin/bash
# Run a source file in the emulator

if [ "$1" = "" ]; then
    echo "usage: run foo.sl"
    exit 1
fi

./slangc < $1 > prog.s
shift
# only peepopt prog.s because it's unsound on hand-written assembly code
cat head.s <(./peepopt prog.s | ./peepopt) foot.s | ../asm/asm > prog.hex
../emulator/scamp -r prog.hex $@
