#!/bin/sh
# Run a source file in the emulator

if [ "$1" = "" ]; then
    echo "usage: run foo.sl"
    exit 1
fi

./slangc < $1 > prog.s
shift
cat head.s prog.s foot.s | ../asm/asm > prog.hex
../emulator/scamp -r prog.hex $@
