#!/bin/bash
# Run an assembled source file in the emulator

set -e

if [ "$1" = "" ]; then
    echo "usage: run foo.sl"
    exit 1
fi

asmsrc=$1

shift
# only peepopt prog.s because it's unsound on hand-written assembly code
cat head.s <(./peepopt $asmsrc | ./peepopt) foot.s | ../asm/asm > prog.hex
../emulator/scamp -r prog.hex $@
