#!/bin/bash
# Run an assembled source file in the emulator

set -e

if [ "$1" = "" ]; then
    echo "usage: srun foo.s"
    exit 1
fi

asmsrc=$1

shift
# only peepopt prog.s because it's unsound on hand-written assembly code
../peepopt $asmsrc | ../peepopt > prog.opt.s
cat head.s prog.opt.s foot.s | ../../asm/asm > prog.hex
cd ..
../emulator/scamp -r test/prog.hex $@
