#!/usr/bin/perl

use strict;
use warnings;

my $usage = "usage: hex2c NAME LENGTH\n";
my $name = shift or die $usage;
my $length = shift or die $usage;

print "#include <stdint.h>\n";
print "uint16_t $name\[$length\] = {";

my @c = <>;

for my $i (0 .. $#c) {
    chomp $c[$i];
    print "\n" if $i%25 == 0;
    print "0x$c[$i]";
    print ", " if $i != $#c;
}

print "\n};\n";
